greetings:
  examples: ["Hello Drago", "Hi there Drago", "Greetings Drago", "Howdy Drago"]
  response: ["Hey there !!"]

goodbye:
  examples: ["Goodbye Drago", "See you later Drago", "Bye Drago"]
  response: ["Goodbye, see you soon!"]

time_query:
  examples: ["What time is it?", "Can you tell me the time?", "What's the current time?"]
  response: ["The current time is {time}."]

weather_query:
  examples: ["what's the weather in delhi?", "tell me the weather in london", "how's the weather today in paris"]
  response: ["{weather}"]


calender_query:
  examples: ["What's on my calendar?", "Do I have any events today?", "Can you check my schedule?"]
  response: ["You have {events} on your calendar today."]

date_query:
  examples: ["What's the date today?", "Can you tell me the date?", "What day is it?"]
  response: ["Today's date is {date}."]